### ISSUE TITLE
React Native - Audio/Video Call Support

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/react-native-chat-sdk#1]
https://forum.cometchat.com/t/react-native-audio-video-call-support/649

**Comment by mayur-bhandari** [comment]
The Audio/Video Call Support for React Native has been added in the latest beta release v2.1.0-beta1. You can follow the documentation here: https://prodocs.cometchat.com/v2.1/docs/react-native-quick-start

**Comment by morph3ux** [comment]
Any updates on this? v2.1.0-beta1 doesn't seem to work on react-native 0.60 nor 0.61. I've tried using it on fresh installs and no success.

**Comment by mayur-bhandari** [comment]
Hello @morph3ux, 

Can you please let us know what exact issue you are facing?

**Comment by mike-van** [comment]
@morph3ux are you facing a problem similar to me [here](https://github.com/cometchat-pro/react-native-chat-sdk/issues/2#issuecomment-611356651) ? I'm also trying to integrate the calling into my application.

**Comment by morph3ux** [comment]
@Mike-Van

Before getting here, I was using yarn and it crashed everytime so I deleted node_modules and installed everything just with npm.

The issue I had was solved by changing the platform version at the top of the pod file where it says 
**Platform :ios, x.x**
Change x.x to 10.0

And then the package installed and **pod install** worked.

Another issue I had was when I tried to run it on a real iOS device, but this solved my issue: https://github.com/jitsi/jitsi-meet/issues/4209

**Comment by morph3ux** [comment]
@mayur-bhandari 
> Hello @morph3ux,
> 
> Can you please let us know what exact issue you are facing?

The problem was with yarn - seems like this package can be installed only with npm :( <-- really sad face

**Comment by mayur-bhandari** [comment]
@morph3ux @Mike-Van 

Hello,


We have completely re-written our calling component and released it in v2.1.0-beta2. Please update the SDK to v2.1.0-beta2.

Documentation: https://prodocs.cometchat.com/v2.1/docs/react-native-quick-start
