### ISSUE TITLE
Error in React Native when trying to fetch previous messages

### ISSUE THREAD

**Issue by shiroganee** [cometchat-pro/react-native-chat-sdk#12]
### Describe the problem

When calling below code, application will crash even though 5 days ago it was working alright

`new CometChat.MessagesRequestBuilder().setLimit(50).setUID(receiverId).build().fetchPrevious(),`

application with crash with two errors in console
> JSON value '306' of type NSNumber cannot be converted to NSString
> Error: {
> message = "Entries must be arrays of the form [key: string, value: string], got: (\n all\n)";
> }
> 

I'm assuming that it is due to how it is being stored in AsyncStorage in React Native or some changes to how it is being sent to RN (as it stopped to work without a reason). Also there is another issue with asyncStorage imported from RN instead of standalone module.

### What was the expected behavior?

Get previous messages without fatal crash

### Reproduction

- create chat between 2 people
- send a message 
- after that try to get all messages

### Environment

- 2.0.12 and 2.1.0-beta
- RN 62.0.x

**Comment by xLesterGG** [comment]
I'm having this problem as well, on **2.0.12**, looks to be trying to store a double into AsyncStorage which doesnt work

**Comment by mayur-bhandari** [comment]
@shiroganee @xLesterGG

Hello,

We have solved this issue and will be releasing a patch for the same.

**Comment by mayur-bhandari** [comment]
@shiroganee @xLesterGG 

Hello, 

This has been resolved in the latest beta release v2.0.13-beta1.
