### ISSUE TITLE
Delete Whole Chat Functionality is Missing 

### ISSUE THREAD

**Issue by SyedHaris94** [cometchat-pro/react-native-chat-sdk#15]
### Describe the problem

is there any waay to delete complete chat of user from cometchat in react native ?

**Comment by mayur-bhandari** [comment]
Hello @SyedHaris94, 

Currently, the SDK only provides a method to delete a single message. We have created a feature request for adding the delete conversation functionality in the SDK. And I have added you to the feature request. We will keep you updated on progress. However, you can use our REST API to delete a conversation for a single user or both the user. I am sharing the link to our REST API Documentation for deleting a conversation. Hope this helps.

REST API Documentation: 
- https://prodocs.cometchat.com/reference#delete-conversation
- https://prodocs.cometchat.com/reference#delete-conversation-for-a-user
