### ISSUE TITLE
Android - appSettings.getRegion

### ISSUE THREAD

**Issue by shiroganee** [cometchat-pro/react-native-chat-sdk#16]
### Describe the problem

When adding:
TypeError: undefined is not an object (evaluating 'u.CometChat.appSettings.getRegion')

### What was the expected behavior?

It doesn't throw that error

### Reproduction

Install it and see yourself
### Environment

2.1.0

**Comment by shiroganee** [comment]
Anyone can help with it? It was working alright and stopped

**Comment by jitvarpatil** [comment]
@shiroganee can you let us know when are you getting this error?

**Comment by shiroganee** [comment]
it does happen for both platform on start
version
2.0.13-beta1

@jitvarpatil

**Comment by mayur-bhandari** [comment]
Hello @shiroganee ,

We are unable to reproduce this at our end. Can you please check with our sample app and let us know if you face the same issue in our sample app.  Also please make sure you are using the latest SDK v2.1.0. Starting v2.1.0, you need to follow the setup docs to ensure that the SDK works seamlessly. Please follow the documentation [here](https://prodocs.cometchat.com/docs/react-native-setup).  

Sample App: https://github.com/cometchat-pro/react-native-chat-app

**Comment by shiroganee** [comment]
@mayur-bhandari okey i got it, thanks for info. It was related to adding event listener before awaiting init on comet chat
