### ISSUE TITLE
CometChat.CallingComponent causes Typescript JSX element type error

### ISSUE THREAD

**Issue by jim-jigx** [cometchat-pro/react-native-chat-sdk#17]
### Describe the problem

Using the audio/video chat in a Typescript app causes the following Typescript error:

JSX element type 'CometChat.CallingComponent' does not have any construct or call signatures. ts(2604)

### What was the expected behavior?

The component can be used without a Typescript error

### Reproduction

It's difficult to show a full repro of the issue but basically see the following:

  const callContainer = useCallback(() => {
      return (
        <View style={viewStyle}>
          <CometChat.CallingComponent callsettings= {callSettings} />
        </View>
      )
  })

In Typescript with the linter enabled, the CometChat.CallingComponent is flagged with the following error:

JSX element type 'CometChat.CallingComponent' does not have any construct or call signatures. ts(2604)

This can be fixed by modifying CometChat.d.ts line 64 to be:L

    // let CallingComponent: callingComponent;
    let CallingComponent: React.Element

### Environment

- @cometchat-pro/react-native-chat": "2.1.0"

**Comment by mayur-bhandari** [comment]
Hello @jim-jigx ,

This issue has been fixed in v2.2.1. Please let us know if you face any other issues.
