### ISSUE TITLE
getJoinedGroups doesn't proceed

### ISSUE THREAD

**Issue by shiroganee** [cometchat-pro/react-native-chat-sdk#19]
### Describe the problem

Whenever calling getJoinedGroups you never get result or error. It just is stuck on that function

### What was the expected behavior?

It should return groups

### Reproduction

call that function after being logged in

### Environment

Version used 2.1.0

**Comment by mayur-bhandari** [comment]
Hello @shiroganee ,

Can you please check if CometChat.getConnectionStatus() returns `connected`. And call getJoinedGroups() only if the status returns `connected`.

**Comment by shiroganee** [comment]
That was the reason! thank you for quick answer @mayur-bhandari
