### ISSUE TITLE
Unable to resolve module `@react-native-community/async-storage` from `node_modules\@cometchat-pro\react-native-chat\CometChat.js`

### ISSUE THREAD

**Issue by jiahong96** [cometchat-pro/react-native-chat-sdk#21]
### Describe the problem
Not able to build Android release bundle successfully. 

`Unable to resolve module @react-native-community/async-storage from node_modules\@cometchat-pro\react-native-chat\CometChat.js: @react-native-community/async-storage could not be found within the project.`

Even after manually installing the `@react-native-community/async-storage`, it requires more dependencies such as `@cometchat-pro/react-native-calls`

### What was the expected behavior?
Installing `@cometchat-pro/react-native-chat` should install the required dependencies along with it. And results in a successful build.

### Reproduction
Upgrade to latest `@cometchat-pro/react-native-chat` version ^2.1.4 and run gradlew bundleRelease.

### Environment
**Expo bare workflow**

Version used: 
```
"react-native": "0.63.2"
"@cometchat-pro/react-native-chat": "^2.1.4"
```

**Comment by mayur-bhandari** [comment]
Hello @jiahong96 ,

Please go through the setup documentation of react-native SDK [here](https://prodocs.cometchat.com/docs/react-native-setup). I hope this helps. 

Thank You.

**Comment by jiahong96** [comment]
Hi @mayur-bhandari thanks for the reply. Didn't notice the latest changes in React Native setup, as before v2.1 there's no need to install additional dependencies. Would be helpful if CometChat team can update the GitHub repo README in sync with the official documentation.
