### ISSUE TITLE
[Android] Release build crash ( :react-native-community_netinfo dependency conflict )

### ISSUE THREAD

**Issue by tr3v3r** [cometchat-pro/react-native-chat-sdk#23]
### Describe the problem

Android release build crashes with error: 

```
Program type already present: com.reactnativecommunity.netinfo.BroadcastReceiverConnectivityReceiver$1
```

> Debug build with metro bundler works fine.

### What was the expected behavior?

No errors during the release build. ( Resolve conflict )

### Reproduction

- Pre-install https://github.com/react-native-netinfo/react-native-netinfo v4.6.0 ( without manual linking )
- run ./gradlew assembleRelease 

![image](https://user-images.githubusercontent.com/23724142/100991655-4f65b780-3564-11eb-850f-782ca3e60290.png)

### Tried solutions

1. exclude NetInfo dependency from `:cometchat-pro_react-native-calls`. But it produces an error on app launch

```
    implementation(project(':cometchat-pro_react-native-calls')) {       
        exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
    }
```
<img width="899" alt="Снимок экрана 2020-12-03 в 11 48 29" src="https://user-images.githubusercontent.com/23724142/100992025-bbe0b680-3564-11eb-8d2c-601a68244018.png">

### Environment

- **Version used:** 2.1.4
- **react-native:** 0.62.2
- **@cometchat-pro/react-native-calls:** 1.0.3
- **@react-native-community/netinfo:** 4.6.0

### Notes

> build.gradle

```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 23
        compileSdkVersion = 29
        targetSdkVersion = 29
        androidXCore = "1.0.2"
    }

....


allprojects {
    repositories {
         ...
        maven { url "https://dl.bintray.com/cometchat/pro" }
    }
}


```

`./gradlew app:dependencies`

![image](https://user-images.githubusercontent.com/23724142/100992676-86889880-3565-11eb-93f6-0413507e595b.png)

**Comment by tr3v3r** [comment]
I've created repo to reproduce

https://github.com/tr3v3r/cometchat-pro-bug-repro

**Comment by dimaportenko** [comment]
I have the exact same issue. I would like to hear what version of `netinfo` library `cometchat-pro_react-native-calls` uses. So I can put the same in my project and don't break anything. 

@tr3v3r Do you know a better place to get feedback? I see nothing happened here in 15 days.

**Comment by dimaportenko** [comment]
there is no crash with "@react-native-community/netinfo": "5.0.0" for me btw

**Comment by tr3v3r** [comment]
> there is no crash with "@react-native-community/netinfo": "5.0.0" for me btw

Thanks! I'll also try to use this version.
Actually, we are communicating via email with cometchat guys. They say that the development team is currently working on this issue and will notify us of any updates.

**Comment by mike-van** [comment]
Hi, so in my case, i found out that there're 2 of my app local dependencies that could cause this assembleRelease failed. anyway I just added this to my app/build.gradle:
```
implementation(project(':cometchat-pro_react-native-calls')) {
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
    }
```
I'm using :
- "@react-native-community/netinfo": 3.2.1, manually linked
- "@react-native-community/async-storage": 1.11.0, manually linked
