### ISSUE TITLE
Unable To Route Direct Calling Audio To Speaker 

### ISSUE THREAD

**Issue by aagam29** [cometchat-pro/react-native-chat-sdk#25]
### Describe the problem

> Unable to route Direct calling audio to Speaker as mentioned in the [docs](https://prodocs.cometchat.com/docs/react-native-calling-direct-calling)
```
let callController = CometChat.CallController.getInstance();
let speakerMode = CometChat.AUDIO_MODE.SPEAKER;
callController.setAudioMode(speakerMode)
```
The audio is still heard in the earpiece only.

### What was the expected behavior?

> callController.setAudioMode(speakerMode) would redirect audio to speaker instead of earpiece.

### Environment
"@cometchat-pro/react-native-calls": "^1.0.3",
"@cometchat-pro/react-native-chat": "^2.1.6",

**Comment by mayur-bhandari** [comment]
Hello @aagam29 ,

Can you please share the code snippet of the callSettingsBuilder() you are using?

**Comment by aagam29** [comment]
Sure, thanks for replying @mayur-bhandari !
Calling this in component's constructor.
```
initializeCometCall() {
    try {
      let sessionID = this.props.groupId;
      let defaultLayout = false;
      let callListener = new CometChat.OngoingCallListener({
        onCallEnded: call => {
          console.log("Init Listener Call Ended:", call);
        },
        onError: error => {
          console.log('Init Listener Error: ', error);
        }
      });
      let callSettings = new CometChat.CallSettingsBuilder()
      .enableDefaultLayout(defaultLayout)
      .showEndCallButton(false)
      .showPauseVideoButton(false)
      .showMuteAudioButton(false)
      .showSwitchCameraButton(false)
      .showAudioModeButton(false)
      .setSessionID(sessionID)
      .setCallEventListener(callListener)
      .build();      
      setTimeout(() => {
        let callController = CometChat.CallController.getInstance();
        callController.pauseVideo(true);
        let speakerMode = CometChat.AUDIO_MODE.SPEAKER;
        callController.setAudioMode(speakerMode)
      }, 2000)
      return callSettings
    }
    catch (error) {
      console.log('Init error', error)
    }
  }
```
  
  Using the component inside render like:
  ```
  <CometChat.CallingComponent callsettings={this.callSettings} onFailure={(e) => { console.log('Some Error Occured', e); }} />
  ```


I have a custom button that turns video on:

```
<TouchableOpacity style={styles.roundButton} onPress={() => !isVideoEnabled ? this._onConnectButtonPress() : this._onEndButtonPress()}>
```

And the corresponding function which is called:

```
_onConnectButtonPress = () => {
    try {
      let callController = CometChat.CallController.getInstance();
      let speakerMode = CometChat.AUDIO_MODE.SPEAKER;
      callController.pauseVideo(false);
      callController.muteAudio(false);
      callController.setAudioMode(speakerMode)
      this.setState({
      })
      console.log('Connect pressed', callController)
      const { cometChatStore, groupId } = this.props;
      cometChatStore.sendCustomMessage(groupId, CUSTOM_TYPES.VIDEO_CALL, {
        connect: true,
        text: 'Video Connected'
      })
      this.setState({
        isVideoEnabled: true,
        isAudioEnabled: true
      })
    }
    catch (error) {
      console.log('Audio/Video Connect Error', error)
      this.setState({
        error: true
      })
    }
  }
  ```
  
  I hope you have the context that you need.

**Comment by mayur-bhandari** [comment]
Hello @aagam29 ,

Thanks for the information. I need a few more details regarding which calling flow are you using? 
-> Default or Direct? (Asking because the title of the issue mentions default but your description mentions direct)

Also, would like to know if you are using the default calling flow? Are you trying to make an audio call or a video call?

**Comment by aagam29** [comment]
Oh @mayur-bhandari, so sorry will update this.
My bad. I'm using direct calling. 
Audio-Video Call using Direct calling.

**Comment by mayur-bhandari** [comment]
Hello @aagam29 ,

We have released an update to our Calling Component. Please update the React Native SDK (@cometchat-pro/react-native-chat) to 2.1.7 & React Native Calling Component (@cometchat-pro/react-native-calls) to 1.0.7. Please let us know if you still face this issue.

**Comment by danishkhalid1** [comment]
Hello @mayur-bhandari ,

**Comment by proveshapyne** [comment]
Hello @aagam29,

Hope this was helpful and the issue has been resolved.
For further technical help, please feel free to write to us at help@cometchat.com

Regards,
Provesha

**Comment by aagam29** [comment]
Awesome!
