### ISSUE TITLE
CometChat.deleteConversation is not a function

### ISSUE THREAD

**Issue by alifarooq96** [cometchat-pro/react-native-chat-sdk#29]
### Describe the problem

> CometChat.deleteConversation is not a function on version 2.3.1. I see the type definition in index.d.ts but it does not work.

### What was the expected behavior?

> The conversation should have been deleted.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> Call thus function:

```
CometChat.deleteConversation(conversationWith, conversationType).then(
    deletedConversation => {
        console.log(deletedConversation);
    }, error => {
        console.log('error while deleting a conversation', error);
    }
);
```

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment
> Please provide the following:

- "@cometchat-pro/react-native-chat" 2.3.1
-  XCode 12.4
- iOS 14.4

**Comment by mayur-bhandari** [comment]
Hello @alifarooq96,

Can you please delete node_modules folder and reinstall the packages using `npm install`. I believe this might be an issue with npm install. Can you please check and let us know if it works for you or not.

**Comment by alifarooq96** [comment]
@mayur-bhandari thanks it worked after a re-install, not sure how the node_modules were only partially updated with the previous npm install. Thanks!
