### ISSUE TITLE
TypeError: e.querySelector is not a function

### ISSUE THREAD

**Issue by mohit4dev** [cometchat-pro/react-native-chat-sdk#3]
Hi,
I am using @cometchat-pro/react-native-chat  v2.0.6
And getting an error while using comet chat.
React v16.9.0
React-Native 0.61.2
Please help me to resolve this issue
![1587635803108](https://user-images.githubusercontent.com/57179148/80086123-e1412700-8576-11ea-9b94-fe6f311b59fc.JPEG)

**Comment by mayur-bhandari** [comment]
This issue has been resolved in our latest release v2.0.8
