### ISSUE TITLE
Android app CRASH: RNCNetInfo.getCurrentState got 2 arguments, expected 3

### ISSUE THREAD

**Issue by Hezron-Nelapati** [cometchat-pro/react-native-chat-sdk#30]
### Describe the problem
Android App crashing while making calls

### What was the expected behavior?

The callscreen should be started.

### Reproduction

The issue is consistent, and is only in android, in IOS working fine.

2022-04-13 15:47:10.560 15258-17303/com.urspace E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.urspace, PID: 15258
    com.facebook.react.bridge.NativeArgumentsParseException: RNCNetInfo.getCurrentState got 2 arguments, expected 3
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:348)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:264)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:923)

### Environment

"react": "16.13.1",
"react-native": "0.61.5",
"@cometchat-pro/react-native-calls": "^2.1.2",
"@cometchat-pro/react-native-chat": "^2.4.1",
"@react-native-community/netinfo": "^8.2.0", [Dependent module]

android/build.gradle -
buildscript {
    ext {
        buildToolsVersion = "29.0.3" //It set by gradle to it's required version
        minSdkVersion = 24
        compileSdkVersion = 30
        targetSdkVersion = 30
        androidXCore = "1.7.0"
    }
    ...
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.3")
         classpath 'com.google.gms:google-services:3.2.1'
    }
}

android/app/build.gradle -
implementation(project(':cometchat-pro_react-native-calls')) {
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-community_netinfo'
    }

**Comment by TirathBhuva** [comment]
Hello @Hezron-Nelapati 
 you are facing this issue because of conflict in the version of react-native-netinfo.  Downgrading the react-native-netinfo version to 4.1.5 should solve this issue

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva Thanks for the help. Will try this and let you know.

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva Thanks, issue is resolved.

**Comment by Hezron-Nelapati** [comment]
Hi, @TirathBhuva as for the suggestion, i was able to run perfectly fine in IOS, but i'm getting below error in IOS. Is there any version which works perfectly fine in both IOS & Android.

RNCNetInfo.getCurrentState was called with 1 arguments but expects 0 arguments.

**Comment by TirathBhuva** [comment]
Hello @Hezron-Nelapati 
 Have you reinstall the pods after changing the version of react-native-netinfo?

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva yes, the pods version is also 4.1.5

**Comment by TirathBhuva** [comment]
Hello @Hezron-Nelapati ,
 Can you check if you are using netinfo package somewhere in your code then try to comment that code out and build your project or can you try building the project after  removing the calling component from your project so that we can understand what is the root cause of this issue.

**Comment by Hezron-Nelapati** [comment]
Hello @TirathBhuva, 

I may not be able to do that, but can you tell that if cometchat is using react native net info as a dependency inside of it, and also currently there are two versions of cometchat v2 & v3, so while developing cometchat does team use react native netinfo, if they are using it can you specify which version of netinfo they are using for both v2 & v3.

Thanks.

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva it would be nice if cometchat can add netinfo as external dependency or update the netinfo version

**Comment by TirathBhuva** [comment]
@Hezron-Nelapati 
Thank you for your suggestion you can add a feature request over [here](https://cometchat.canny.io/). Also, the react-native NetInfo is a dependency in CometCchat calls packages, not the chat SDK so it will be the same in v2 and v3. The version of NetInfo that we use is 4.1.5.

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva

 I know, this repo is about cometchat chat, I'm posting an issue here as there is no repo for discussion for calls package.

I see, but even upgrading the dependency and checking the stability will take a lot more time. 

The main issue here is the method signature of getCurrentState method in netinfo package has been changed in newer versions. You can check the method signature in the package repo.

So, i think it would be better if,

1. If cometchat calls is just calling the methods of package instead of building the code with dependency, i suggest that you can match the getCurrentState method your using with latest getCurrentState method signature 

2. If you're building the code with the dependency, i think changing the method name and Module Name would solve the issue because the issue is only occurring in Android as the Java code is verifying method signature, and the users can use new netinfo versions without any issues.

Both methods take less time, and you don't have to worry about instability of the package. As the users need to use a new version of netinfo to know network status better, and they are being held back because of your dependency conflicts. 

So I would appreciate it if you could take time and fix this issue, as it helps solving dependency conflicts.

**Comment by TirathBhuva** [comment]
@Hezron-Nelapati  i agree with you and i will make a note of this. Also i will again suggest you to create a feature request over [here](https://cometchat.canny.io/) so that you can get notified when every we take this up

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva 

Sure, I'll make feature requests, but it's just that in our case we need to use both the netinfo new version and cometchat.

So, it would be helpful if you can at least make a patch fix.

Thank you.

**Comment by Hezron-Nelapati** [comment]
@TirathBhuva Made this feature request https://cometchat.canny.io/sdks-apis/p/move-react-native-net-info-as-external-dependency.

It would be nice, if anyone from your team can take a quick look and come up with a solution fast.

**Comment by Hezron-Nelapati** [comment]
Reopened just in case, as it will be easier to look if it is in open status.

**Comment by Vishalgihub** [comment]
![WhatsApp Image 2024-01-11 at 11 51 01 AM](https://github.com/cometchat/react-native-chat-sdk/assets/142166712/13c72f8a-b22a-4cb4-bbf7-c68784f93bfa)

Hello i can install this latestversion of 
 "@cometchat-pro/react-native-calls": "^3.0.4",
    "@cometchat-pro/react-native-chat": "^3.0.13",
    
    this is the netinfo version:
    "@react-native-community/netinfo": "^9.3.7",
    
    and my react-native version is     "react-native": "0.68.0",


but when i videocall to another person then he can pickup the call then it can be a show this error 
please help

**Comment by ketanyekale** [comment]
Seems it was missed if you are still facing this issue please create a [support ticket](https://help.cometchat.com/hc/en-us) or try with the latest v4 SDKs and Sample apps.
