### ISSUE TITLE
Release a new version or add setup instructions to make cometchat work with latest react native versions

### ISSUE THREAD

**Issue by Hezron-Nelapati** [cometchat-pro/react-native-chat-sdk#31]
### Describe the problem

Currently, we have moved our code to RN0.68, i was facing gradle maven plugin not found. The issue was from cometchat calls package.

### What was the expected behavior?

The code should build without errors.

### Reproduction

1.Make a new rn project of version 0.68.2
2.add cometchat as dependency
3.try to build the code in android

### Environment

RN0.68
CometChat - v2.4.1
Calls - v2.1.2

**Comment by Hezron-Nelapati** [comment]
I found some blogs on the net, i was able to build the code with these changes, 

diff --git a/node_modules/@cometchat-pro/react-native-calls/android/build.gradle b/node_modules/@cometchat-pro/react-native-calls/android/build.gradle
index 8d932eb..4cfc921 100644
--- a/node_modules/@cometchat-pro/react-native-calls/android/build.gradle
+++ b/node_modules/@cometchat-pro/react-native-calls/android/build.gradle
@@ -20,7 +20,7 @@ def safeExtGet(prop, fallback) {
 }
 
 apply plugin: 'com.android.library'
-apply plugin: 'maven'
+apply plugin: 'maven-publish'
 
 buildscript {
     // The Android Gradle plugin is only required when opening the android folder stand-alone.
@@ -42,7 +42,7 @@ buildscript {
 }
 
 apply plugin: 'com.android.library'
-apply plugin: 'maven'
+apply plugin: 'maven-publish'
 
 android {
     compileSdkVersion safeExtGet('compileSdkVersion', DEFAULT_COMPILE_SDK_VERSION)
@@ -118,7 +118,8 @@ afterEvaluate { project ->
     task androidJavadoc(type: Javadoc) {
         source = android.sourceSets.main.java.srcDirs
         classpath += files(android.bootClasspath)
-        classpath += files(project.getConfigurations().getByName('compile').asList())
+        project.getConfigurations().getByName('implementation').setCanBeResolved(true)
+        classpath += files(project.getConfigurations().getByName('implementation').asList())
         include '**/*.java'
     }
 
@@ -147,12 +148,12 @@ afterEvaluate { project ->
         archives androidJavadocJar
     }
 
-    task installArchives(type: Upload) {
-        configuration = configurations.archives
-        repositories.mavenDeployer {
-            // Deploy to react-native-event-bridge/maven, ready to publish to npm
-            repository url: "file://${projectDir}/../android/maven"
-            configureReactNativePom pom
-        }
-    }
+//    task installArchives(type: Upload) {
+//        configuration = configurations.archives
+//        repositories.mavenDeployer {
+//            // Deploy to react-native-event-bridge/maven, ready to publish to npm
+//            repository url: "file://${projectDir}/../android/maven"
+//            configureReactNativePom pom
+//        }
+//    }
 }

I know this not totally right, but it would be helpful if you can come up with a fix

**Comment by msl2000** [comment]
I agree with this. I am getting errors for ios builds at the moment where the call package can't be imported by the chat package due to the following error:

Requiring module [node_modules/@cometchat-pro/react-native-calls/dist/index.js](mailto:node_modules/@cometchat-pro/react-native-calls/dist/index.js), which threw an exception: TypeError: Cannot set property userAgent of #<WorkerNavigator> which has only a getter


    "@cometchat-pro/react-native-calls": "3.0.2",
    "@cometchat-pro/react-native-chat": "^3.0.11",
    "react-native": "0.70.4",

**Comment by ketanyekale** [comment]
This has been fixed with v4. Please try the latest version of react native SDK
