### ISSUE TITLE
Edit Message listener not working

### ISSUE THREAD

**Issue by shridharrai-nickelfox** [cometchat-pro/react-native-chat-sdk#32]
### Describe the problem
I added the real time listeners for edited messages and it is working fine before yesterday. But from yesterday the edit message listeners are not firing when i am editing the messages

### What was the expected behavior?
The edit message listeners should fired when someone is editing a message in the group

### Environment

> Please provide the following:

- **Version used:**3.0.11
- **Other modules/plugins/libraries that might be involved:**

**Comment by proveshapyne** [comment]
Hi @shridharrai-nickelfox ,

We have reached out to you over email to investigate this. We can continue the conversation there.
