### ISSUE TITLE
undefined is not an object (evaluating 'S.CometChat.appSettings.shouldAutoEstablishSocketConnection')

### ISSUE THREAD

**Issue by ChiragAtharva** [cometchat-pro/react-native-chat-sdk#34]
###  ERROR  TypeError: undefined is not an object (evaluating 'S.CometChat.appSettings.shouldAutoEstablishSocketConnection')

> I have installed cometchat library with as below for chat
"@cometchat/chat-sdk-react-native": "4.0.5",
"@react-native-community/netinfo": "7.1.7",
"react-native-background-timer": "2.4.1",

then initialize app with below code
const appID: string = configJSON.appId,
      region: string = configJSON.region,
      appSetting: CometChat.AppSettings = new CometChat.AppSettingsBuilder()
        .subscribePresenceForAllUsers()
        .setRegion(region)
        .autoEstablishSocketConnection(true)
        .build();

    try {
      await CometChat.init(appID, appSetting);
    } catch (error) {
      this.showAlert(
        "",
        "Initialization failed, Please try close screen and open again.",
      );
    }
    
    and i got  
    ERROR  TypeError: undefined is not an object (evaluating 'S.CometChat.appSettings.shouldAutoEstablishSocketConnection')
    
### What was the expected behavior?
Error should not come and app have to run properly

### Environment
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.80 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: file:./packages/blocks/core/node_modules/react-native => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

![simulator_screenshot_D531C8C9-3472-4663-BDA0-AA6B06F010BF](https://github.com/cometchat/react-native-chat-sdk/assets/79321446/9f34e690-fa44-49a3-983f-89f35d61903e)

**Comment by ChiragAtharva** [comment]
Hello Team,
I have found the problem and solution
the problem is - CometChat.init(appID, appSetting) 
done on inside the another screen and not on app launch screen

solution - added this initialization on app launch first screen and then it's working fine.

Thank you.

**Comment by soldatov-ss** [comment]
> Hello Team, I have found the problem and solution the problem is - CometChat.init(appID, appSetting) done on inside the another screen and not on app launch screen
> 
> solution - added this initialization on app launch first screen and then it's working fine.
> 
> Thank you.

could you give a bit more details please?
Don't you initialize this in the App.tsx?
