### ISSUE TITLE
Getting error while accepting a call.

### ISSUE THREAD

**Issue by mayur-bhandari** [cometchat-pro/react-native-chat-sdk#4]
The issue has been described in the below forum tickets.

https://forum.cometchat.com/t/invariant-violation-native-modue-cannot-be-null/1127/5

https://forum.cometchat.com/t/error-on-initiating-calls-in-latest-sample-react-native-app/1260

**Comment by shaheenshaikh6** [comment]
Hi Mayur,
Any updates for this issue. I am integrated cometchat calls and geting same error when initiating call. 

Thanks

**Comment by mike-van** [comment]
Hi @mayur-bhandari , any updates on this issue?

**Comment by dumbre-prasad** [comment]
HI @mayur-bhandari  Can you please give an update on this??
@mike-van do you have any solution to fix this issue?

**Comment by mayur-bhandari** [comment]
@Mike-Van @dumbre-prasad @shaheenshaikh6 

Hello,

We have completely re-written our calling component and released it in v2.1.0-beta2. Please update the SDK to v2.1.0-beta2.

Documentation: https://prodocs.cometchat.com/v2.1/docs/react-native-quick-start

**Comment by roshnigupta123** [comment]
Hi @mayur-bhandari, 
The callling component gives an error while accepting the call. Please help me. The application is crashed when I accept the call.  How can I solve it?
This version is not working on my project 2.1.0-beta2
