### ISSUE TITLE
Task :app:transformClassesWithMultidexlistForDebug FAILED

### ISSUE THREAD

**Issue by rohitkum28** [cometchat-pro/react-native-chat-sdk#5]
Hi,

I recently tried updating the cometchat library to version **2.0.8** from **2.0.7** to fix [this issue](https://github.com/cometchat-pro/react-native-chat-sdk/issues/3). But, now I am not able to build my project on android because of ```Task :app:transformClassesWithMultidexlistForDebug FAILED``` error.

On investigating further, I realised it is being caused because of **"react-native-google-signin": "^2.0.0"**.

I am using Google-signin in my application and was using the **"@react-native-community/google-signin": "^4.0.0"** which is the recommended version as per [documentation](https://github.com/react-native-community/google-signin) for react-native >=0.60

So, using the two different version of the same library is causing the above error. Is there any reason to use an old version of this library as it also gives the following warning:

    The following packages use deprecated "rnpm" config that will stop working from next release

**Environment:**
    "react": "16.9.0",
    "react-native": "0.61.5",
    "@cometchat-pro/react-native-chat": "^2.0.8"

Please, let me how this can be fixed as this has caused a blocker in our current project.

**Comment by mayur-bhandari** [comment]
Hello @rohitkum28 ,

We have completely re-written our calling component and released it in v2.1.0-beta2. Please update the SDK to v2.1.0-beta2.

Documentation: https://prodocs.cometchat.com/v2.1/docs/react-native-quick-start
