### ISSUE TITLE
Unable to install package with yarn

### ISSUE THREAD

**Issue by fortunee** [cometchat-pro/react-native-chat-sdk#6]
Running 

`npm install @cometchat-pro/react-native-chat@2.0.8 --save` as stated in the documentation works fine

However, I'm not using npm package manager. I'm using and yarn and when I run 

`yarn add @cometchat-pro/react-native-chat@2.0.8` 

I get an error. 👇 
> Error An unexpected error occurred: "ENOENT: no such file or directory, scandir

**Comment by mayur-bhandari** [comment]
Hello @fortunee ,

Can you please try installing the latest SDK v2.1.0 using yarn? Please let us know if you still face the same issue.

**Comment by fortunee** [comment]
Thanks, @mayur-bhandari. I've actually moved on from this and I stuck to using npm.
